server:
  port: 8082

spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb

  sleuth:
    sampler:
      probability: 1.0  # Trace 100% of requests

  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    root: info
    com.example.productService: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

info:
  app:
    name: product-service
    version: 1.0

product:
  message: "Hello from product-service development profile!"
